version: '3.8'

networks:
  openfga:
    driver: bridge

services:
  postgres:
    image: postgres:17
    container_name: postgres
    networks:
      - openfga
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.local/.env.postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]   # here database_username is 'postgres' is hardcoded
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    depends_on:
      postgres:
        condition: service_healthy
    image: openfga/openfga:latest
    container_name: migrate
    env_file:
      - .envs/.local/.env.openfga
    command: migrate
    networks:
      - openfga

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga
    env_file:
      - .envs/.local/.env.openfga
    command: run
    networks:
      - openfga
    ports:
      # Needed for the http server
      - "8080:8080"
      # Needed for the grpc server (if used)
      - "8081:8081"
      # Needed for the playground (Do not enable in prod!)
      - "3000:3000"

  django-web:
    build: ./filehub
    volumes:
      - ./filehub:/app
    container_name: django-docker
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .envs/.local/.env.django
      - .envs/.local/.env.postgres
    networks:
    - openfga

volumes:
  postgres_data:
