networks:
  openfga:
    driver: bridge

volumes:
  postgres_data_local:

services:
  postgres:
    image: postgres:17
    container_name: openfga-postgres
    networks:
      - openfga
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    env_file:
      - .envs/.local/.env.postgres.temp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openfga"]
      interval: 5s
      timeout: 5s
      retries: 5

  openfga-migrate:
    image: openfga/openfga:latest
    container_name: openfga-migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - openfga
    env_file:
      - .envs/.local/.env.openfga.temp
    command: >
      migrate
      --datastore-engine postgres
      --datastore-uri postgres://openfga:openfga@openfga-postgres:5432/openfga?sslmode=disable

  openfga:
    image: openfga/openfga:latest
    container_name: openfga
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    networks:
      - openfga
    env_file:
      - .envs/.local/.env.openfga.temp
      - .envs/.local/.env.postgres.temp
    command: >
      run
      --datastore-engine postgres
      --datastore-uri postgres://openfga:openfga@openfga-postgres:5432/openfga?sslmode=disable
    ports:
      - "8080:8080" # HTTP API
      - "8081:8081" # gRPC API
      - "3000:3000" # Playground (dev only)

  django-web:
    build: ./filehub
    container_name: django-docker
    volumes:
      - ./filehub:/app
    ports:
      - "8000:8000"
    depends_on:
      openfga:
        condition: service_started
    env_file:
      - .envs/.local/.env.django
      - .envs/.local/.env.postgres.temp
      - .envs/.local/.env.openfga.temp
    networks:
      - openfga
