networks:
  openfga:
    driver: bridge

volumes:
  postgres_data_local:

services:
  postgres:
    image: postgres:17
    container_name: openfga-postgres
    networks:
      - openfga
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    env_file:
      - .envs/.local/.env.postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openfga"]
      interval: 5s
      timeout: 5s
      retries: 5

  openfga-migrate:
    image: openfga/openfga:latest
    container_name: openfga-migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - openfga
    env_file:
      - .envs/.local/.env.openfga
    command: migrate

  openfga:
    image: openfga/openfga:latest
    container_name: openfga
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    networks:
      - openfga
    env_file:
      - .envs/.local/.env.openfga
      - .envs/.local/.env.postgres
    command: run
    ports:
      - "8080:8080" # HTTP API
      - "8081:8081" # gRPC API
      - "3000:3000" # Playground (dev only)

  django-web:
    build: ./filehub
    container_name: django-docker
    volumes:
      - ./filehub:/app
    ports:
      - "8000:8000"
    depends_on:
      openfga:
        condition: service_started
    env_file:
      - .envs/.local/.env.django
      - .envs/.local/.env.postgres
      - .envs/.local/.env.openfga
    networks:
      - openfga

  openfga-cli:
    image: openfga/cli:latest
    networks:
      - openfga
    environment:
      - FGA_API_URL=http://openfga:8080
    volumes:
      - ./stores:/data